---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: true
  vars:
    apt_cache_valid_time: 300
  tasks:
    - name: Find docker binary
      ansible.builtin.stat:
        path: /usr/bin/docker
      register: docker_binary

    - name: Ensure docker binary exists
      ansible.builtin.assert:
        that:
          - docker_binary.stat.exists
